--
-- 01_schema.sql
--
-- GENERATED by scripts/02_generate_ddl.py on 2026-09-14T09:50:07
-- Sources: data/profile/profile.json  +  db2/ddl/overlay.json
--
-- Do not edit this file. Change the overlay (design decisions) or re-profile
-- (data reality), then regenerate. Hand edits are lost on the next run.
--

CREATE SCHEMA NBKI;

-- A dedicated read-only principal is what Fabric connects as. Least privilege
-- is not optional for a regulated bank, and it is the first thing their security
-- team will ask about.
-- (Create the OS/LDAP user first; Db2 LUW authenticates against the operating system.)
-- GRANT CONNECT ON DATABASE TO USER FABRICRO;
-- GRANT SELECTIN ON SCHEMA NBKI TO USER FABRICRO;
