--
-- 02_tables.sql
--
-- GENERATED by scripts/02_generate_ddl.py on 2026-09-14T09:50:07
-- Sources: data/profile/profile.json  +  db2/ddl/overlay.json
--
-- Do not edit this file. Change the overlay (design decisions) or re-profile
-- (data reality), then regenerate. Hand edits are lost on the next run.
--

-- Customer master. One row per client.
-- Source: users_data.csv

CREATE TABLE NBKI.CUSTOMERS (
    CUSTOMER_ID              INTEGER NOT NULL,
    CURRENT_AGE              SMALLINT,
    RETIREMENT_AGE           SMALLINT,
    BIRTH_YEAR               SMALLINT,
    BIRTH_MONTH              SMALLINT,
    GENDER                   VARCHAR(8),
    ADDRESS                  VARCHAR(200),
    LATITUDE                 DECIMAL(9,4),
    LONGITUDE                DECIMAL(9,4),
    PER_CAPITA_INCOME        DECIMAL(15,2),
    YEARLY_INCOME            DECIMAL(15,2),
    TOTAL_DEBT               DECIMAL(15,2),
    CREDIT_SCORE             SMALLINT,
    NUM_CREDIT_CARDS         SMALLINT,
    LAST_UPDATED_TS          TIMESTAMP NOT NULL GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
);


-- Card master. Many cards per customer.
-- Source: cards_data.csv

CREATE TABLE NBKI.CARDS (
    CARD_ID                  INTEGER NOT NULL,
    CUSTOMER_ID              INTEGER NOT NULL,
    CARD_BRAND               VARCHAR(32),
    CARD_TYPE                VARCHAR(32),
    CARD_NUMBER              VARCHAR(24),
    EXPIRES_YM               VARCHAR(7),
    CVV                      VARCHAR(8),
    HAS_CHIP                 VARCHAR(8),
    NUM_CARDS_ISSUED         SMALLINT,
    CREDIT_LIMIT             DECIMAL(15,2),
    ACCT_OPEN_YM             VARCHAR(7),
    YEAR_PIN_LAST_CHANGED    SMALLINT,
    CARD_ON_DARK_WEB         VARCHAR(8),
    LAST_UPDATED_TS          TIMESTAMP NOT NULL GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP,
    CONSTRAINT PK_CARDS PRIMARY KEY (CARD_ID),
    CONSTRAINT FK_CARDS_CUSTOMERS_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES NBKI.CUSTOMERS (CUSTOMER_ID)
);

COMMENT ON COLUMN NBKI.CARDS.CARD_NUMBER IS 'Synthetic. Never cast a PAN to a number.';
COMMENT ON COLUMN NBKI.CARDS.EXPIRES_YM IS 'MM/YYYY. No day component, so DATE would invent one.';
COMMENT ON COLUMN NBKI.CARDS.CVV IS 'Zero-padded: 4 values in the real file begin with 0.';

CREATE INDEX NBKI.IX_CARDS_CUSTOMER ON NBKI.CARDS (CUSTOMER_ID);


-- Card transaction fact. The large table; ~13M rows in the real dataset.
-- Source: transactions_data.csv

CREATE TABLE NBKI.TRANSACTIONS (
    TRANSACTION_ID           BIGINT NOT NULL,
    TXN_TS                   TIMESTAMP NOT NULL,
    CUSTOMER_ID              INTEGER NOT NULL,
    CARD_ID                  INTEGER NOT NULL,
    AMOUNT                   DECIMAL(15,2) NOT NULL,
    USE_CHIP                 VARCHAR(32),
    MERCHANT_ID              INTEGER,
    MERCHANT_CITY            VARCHAR(64),
    MERCHANT_STATE           VARCHAR(64),
    MERCHANT_ZIP             VARCHAR(16),
    MCC_CODE                 VARCHAR(8) NOT NULL,
    ERROR_FLAGS              VARCHAR(128),
    LAST_UPDATED_TS          TIMESTAMP NOT NULL GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP,
    CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT FK_TRANSACTIONS_CUSTOMERS_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES NBKI.CUSTOMERS (CUSTOMER_ID),
    CONSTRAINT FK_TRANSACTIONS_CARDS_2 FOREIGN KEY (CARD_ID) REFERENCES NBKI.CARDS (CARD_ID)
);

COMMENT ON COLUMN NBKI.TRANSACTIONS.TXN_TS IS 'Renamed: DATE is a Db2 reserved word.';
COMMENT ON COLUMN NBKI.TRANSACTIONS.AMOUNT IS 'DECIMAL, never FLOAT. Control totals must tie exactly.';
COMMENT ON COLUMN NBKI.TRANSACTIONS.MERCHANT_STATE IS 'Not a US state code. The column mixes 2-letter US states with full country names; the longest observed is ''Saint Vincent and the Grenadines'' at 32 characters. 11.75% are null. VARCHAR(16) truncated it. Sized to 64 for headroom.';
COMMENT ON COLUMN NBKI.TRANSACTIONS.MERCHANT_ZIP IS 'Arrives float-formatted as ''58523.0'' — the source already treated a postcode as a number, which is also why the leading zeros are gone (lowest observed is 1001, i.e. Massachusetts 01001). The ''.0'' is stripped in prepare; the lost leading zero ca...';

-- The watermark predicate hits this on every incremental run.
CREATE INDEX NBKI.IX_TXN_TS ON NBKI.TRANSACTIONS (TXN_TS);
-- Fabric filters on this. Without it, every run is a table scan.
CREATE INDEX NBKI.IX_TXN_WATERMARK ON NBKI.TRANSACTIONS (LAST_UPDATED_TS);
CREATE INDEX NBKI.IX_TXN_CUSTOMER ON NBKI.TRANSACTIONS (CUSTOMER_ID);


-- Merchant category dimension, flattened from a JSON code->description map.
-- Source: mcc_codes.json

CREATE TABLE NBKI.MCC_CODES (
    MCC_CODE                 VARCHAR(8) NOT NULL,
    MCC_DESCRIPTION          VARCHAR(256),
    LAST_UPDATED_TS          TIMESTAMP NOT NULL GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP,
    CONSTRAINT PK_MCC_CODES PRIMARY KEY (MCC_CODE)
);


-- Fraud labels, flattened from {'target': {txn_id: 'Yes'|'No'}}. Partial coverage by design.
-- Source: train_fraud_labels.json

CREATE TABLE NBKI.FRAUD_LABELS (
    TRANSACTION_ID           BIGINT NOT NULL,
    IS_FRAUD                 VARCHAR(8) NOT NULL,
    LAST_UPDATED_TS          TIMESTAMP NOT NULL GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP,
    CONSTRAINT PK_FRAUD_LABELS PRIMARY KEY (TRANSACTION_ID)
);

