--
-- 03_tables_optional.sql
--
-- GENERATED by scripts/02_generate_ddl.py on 2026-09-14T09:50:07
-- Sources: data/profile/profile.json  +  db2/ddl/overlay.json
--
-- Do not edit this file. Change the overlay (design decisions) or re-profile
-- (data reality), then regenerate. Hand edits are lost on the next run.
--

-- Optional tables. Create these only if the corresponding dataset was
-- downloaded. They are separated so a core load never depends on them.

-- IBM AML set. A single wide table whose only job is volume.
-- No natural key in the source, so a generated identity column supplies one.
-- Source: HI-Small_Trans.csv
-- OPTIONAL: only created when this dataset has been downloaded.

CREATE TABLE NBKI.AML_TRANSACTIONS (
    AML_TXN_ID               BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TXN_TS                   TIMESTAMP NOT NULL,
    FROM_BANK                VARCHAR(16) NOT NULL,
    ACCOUNT_FROM             VARCHAR(24) NOT NULL,
    TO_BANK                  VARCHAR(16) NOT NULL,
    ACCOUNT_TO               VARCHAR(24) NOT NULL,
    AMOUNT_RECEIVED          DECIMAL(23,6) NOT NULL,
    RECEIVING_CURRENCY       VARCHAR(32),
    AMOUNT_PAID              DECIMAL(23,6) NOT NULL,
    PAYMENT_CURRENCY         VARCHAR(32),
    PAYMENT_FORMAT           VARCHAR(32),
    IS_LAUNDERING            SMALLINT,
    LAST_UPDATED_TS          TIMESTAMP NOT NULL GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP,
    CONSTRAINT PK_AML_TRANSACTIONS PRIMARY KEY (AML_TXN_ID)
);

COMMENT ON COLUMN NBKI.AML_TRANSACTIONS.TXN_TS IS 'A real timestamp - this is what makes the watermark clean.';
COMMENT ON COLUMN NBKI.AML_TRANSACTIONS.FROM_BANK IS 'Zero-padded bank code. Text.';
COMMENT ON COLUMN NBKI.AML_TRANSACTIONS.ACCOUNT_TO IS 'The source header contains the name ''Account'' TWICE, literally. This is the second one (position 4, zero-based), which the profiler disambiguates as ''Account_dup4''. It is NOT called ''Account.1'' — that is the pandas convention, and assuming it ...';
COMMENT ON COLUMN NBKI.AML_TRANSACTIONS.AMOUNT_RECEIVED IS 'Scale 6, not 2. 148,151 rows in HI-Small carry more than two decimal places (the crypto rows go down to 0.000001), so DECIMAL(19,2) would round them to 0.00 on load — no error, no rejected row, just quietly missing money and control totals that no l...';
COMMENT ON COLUMN NBKI.AML_TRANSACTIONS.AMOUNT_PAID IS 'Same reasoning as AMOUNT_RECEIVED.';

CREATE INDEX NBKI.IX_AML_TS ON NBKI.AML_TRANSACTIONS (TXN_TS);
CREATE INDEX NBKI.IX_AML_WATERMARK ON NBKI.AML_TRANSACTIONS (LAST_UPDATED_TS);

