--
-- 99_drop.sql
--
-- GENERATED by scripts/02_generate_ddl.py on 2026-09-14T09:50:07
-- Sources: data/profile/profile.json  +  db2/ddl/overlay.json
--
-- Do not edit this file. Change the overlay (design decisions) or re-profile
-- (data reality), then regenerate. Hand edits are lost on the next run.
--

-- Tear-down, in reverse dependency order. Used by the demo reset script.

DROP TABLE NBKI.AML_TRANSACTIONS;
DROP TABLE NBKI.FRAUD_LABELS;
DROP TABLE NBKI.MCC_CODES;
DROP TABLE NBKI.TRANSACTIONS;
DROP TABLE NBKI.CARDS;
DROP TABLE NBKI.CUSTOMERS;

-- DROP SCHEMA NBKI RESTRICT;
