#!/usr/bin/env python3
"""
02_generate_ddl.py — merge the data profile with the design overlay to produce Db2 DDL.

The split
---------
  profile.json   what IS in the files      (discovered, scripts/01_profile.py)
  overlay.json   what we WANT in Db2       (authored, db2/ddl/overlay.json)

Neither alone is enough. The profiler cannot know that `client_id` is a foreign key
or that `date` collides with a Db2 reserved word. The overlay cannot know that a
column turned out to be 200 characters wide.

Generating rather than hand-writing the DDL means the schema cannot silently drift
away from the data. If the real Kaggle files differ from the fixtures, this fails
loudly with the specific mismatch instead of producing DDL that breaks at load time.

Usage:
    ./scripts/02_generate_ddl.py
    ./scripts/02_generate_ddl.py --strict     # any warning becomes an error
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
PROFILE = REPO_ROOT / "data" / "profile" / "profile.json"
OVERLAY = REPO_ROOT / "db2" / "ddl" / "overlay.json"
DDL_DIR = REPO_ROOT / "db2" / "ddl"

HEADER = """--
-- {filename}
--
-- GENERATED by scripts/02_generate_ddl.py on {ts}
-- Sources: data/profile/profile.json  +  db2/ddl/overlay.json
--
-- Do not edit this file. Change the overlay (design decisions) or re-profile
-- (data reality), then regenerate. Hand edits are lost on the next run.
--
"""


class Warn:
    def __init__(self) -> None:
        self.items: list[str] = []

    def add(self, msg: str) -> None:
        self.items.append(msg)
        print(f"  WARN: {msg}", file=sys.stderr)


def load_json(path: Path, what: str) -> Any:
    if not path.exists():
        print(f"ERROR: {what} not found at {path}", file=sys.stderr)
        if path == PROFILE:
            print("       Run ./scripts/01_profile.py first (which needs data in data/raw).",
                  file=sys.stderr)
        sys.exit(1)
    return json.loads(path.read_text(encoding="utf-8"))


def profile_index(profiles: list[dict]) -> dict[str, dict]:
    return {p["file"]: p for p in profiles if "error" not in p}


def resolve_column(
    src_name: str, spec: dict, prof_cols: dict[str, dict], table: str, warn: Warn,
    cross_check: bool = True
) -> tuple[str, str, bool, str | None]:
    """Return (db2_name, db2_type, nullable, comment) for one column."""
    db2_name = spec.get("name", src_name.upper().replace(" ", "_").replace(".", "_"))
    nullable = spec.get("nullable", True)
    comment = spec.get("comment")
    # A stated reason means the divergence from the profile is a decision, not a
    # surprise. Decisions get reported as notes; surprises get reported as warnings.
    reason = spec.get("override_reason")

    pc = prof_cols.get(src_name)
    if pc is None and cross_check:
        warn.add(f"{table}.{src_name}: column not present in the profiled data "
                 f"(available: {', '.join(sorted(prof_cols)[:8])}...)")

    if "type" in spec:
        db2_type = spec["type"]
        # The overlay wins, but say so when it contradicts the observed data —
        # that is exactly the signal that the real files differ from expectation.
        if pc:
            suggested = pc["suggested_db2_type"]
            if _base(suggested) != _base(db2_type):
                benign = _compatible(suggested, db2_type) or reason
                msg = (f"{table}.{src_name}: overlay says {db2_type}, profile suggests "
                       f"{suggested} ({pc['suggestion_reasoning']})")
                if reason:
                    msg += f" — deliberate: {reason}"
                if benign:
                    print(f"  note: {msg}")
                else:
                    warn.add(msg)
            # A width the data will not fit into is a hard error waiting to happen.
            if db2_type.startswith("VARCHAR") and pc["str_max_len"]:
                declared = int(db2_type[8:-1])
                if pc["str_max_len"] > declared:
                    warn.add(f"{table}.{src_name}: VARCHAR({declared}) is too narrow — "
                             f"observed values up to {pc['str_max_len']} chars")

            # The same check for DECIMAL, which is more dangerous because the two
            # failure modes are not symmetrical:
            #   too few integer digits -> Db2 rejects the row, and you find out
            #   too small a scale      -> Db2 ROUNDS silently, and you do not
            # The second one loses money without producing an error anywhere, so
            # it is the one worth being noisy about.
            if _base(db2_type) == "DECIMAL" and "(" in db2_type:
                try:
                    dp, ds = (int(x) for x in db2_type[db2_type.index("(") + 1:-1].split(","))
                except ValueError:
                    dp = ds = None
                if ds is not None:
                    obs_scale = pc.get("max_scale") or 0
                    obs_int = pc.get("max_int_digits") or 0
                    if obs_scale > ds:
                        warn.add(
                            f"{table}.{src_name}: DECIMAL({dp},{ds}) has scale {ds} but the data "
                            f"carries up to {obs_scale} decimal places — Db2 will ROUND on load, "
                            f"silently, with no rejected row. Control totals will stop tying. "
                            f"Use scale {obs_scale}")
                    if obs_int > (dp - ds):
                        warn.add(
                            f"{table}.{src_name}: DECIMAL({dp},{ds}) leaves {dp - ds} integer "
                            f"digits but the data needs {obs_int} — rows will be rejected")
            if not nullable and pc["nulls"] > 0:
                warn.add(f"{table}.{src_name}: declared NOT NULL but profile found "
                         f"{pc['nulls']:,} nulls ({pc['null_pct']:.2f}%)")
    elif pc:
        db2_type = pc["suggested_db2_type"]
    else:
        db2_type = "VARCHAR(128)"
        warn.add(f"{table}.{src_name}: no overlay type and no profile — defaulting to VARCHAR(128)")

    return db2_name, db2_type, nullable, comment


def _base(t: str) -> str:
    return t.split("(")[0].strip().upper()


def _compatible(suggested: str, declared: str) -> bool:
    """Is the overlay type a sane widening of what was observed?"""
    ints = ["SMALLINT", "INTEGER", "BIGINT"]
    s, d = _base(suggested), _base(declared)
    if s in ints and d in ints:
        return ints.index(d) >= ints.index(s)          # widening is fine
    if s in ("DECIMAL", "FLOAT") and d == "DECIMAL":
        return True
    if s == "VARCHAR" and d in ("VARCHAR", "CHAR"):
        return True
    # A profiler that saw only zero-padded text where we want a number is a real
    # conflict, not a widening.
    return False


def emit_table(t: dict, prof: dict | None, overlay: dict, warn: Warn) -> str:
    schema = overlay["schema"]
    table = t["table"]
    wm = overlay["watermark"]
    lines: list[str] = []

    comment = t.get("comment")
    if isinstance(comment, list):
        for c in comment:
            lines.append(f"-- {c}")
    elif comment:
        lines.append(f"-- {comment}")
    lines.append(f"-- Source: {t['source_file']}")
    if t.get("optional"):
        lines.append("-- OPTIONAL: only created when this dataset has been downloaded.")
    lines.append("")

    prof_cols = {c["name"]: c for c in prof["columns"]} if prof and "columns" in prof else {}

    col_defs: list[str] = []
    col_comments: list[tuple[str, str]] = []

    if "synthetic_key" in t:
        sk = t["synthetic_key"]
        col_defs.append(f"    {sk['name']:<24} {sk['ddl']}")

    src_map = t.get("columns") or {}
    is_json = t.get("source_kind") in ("flat_map", "nested_map")
    if is_json:
        src_map = t.get("json_columns", {})
        # JSON files are profiled as documents, not column sets, so there is
        # nothing to cross-check against here.
        prof_cols = {}

    for src_name, spec in src_map.items():
        name, typ, nullable, ccomment = resolve_column(
            src_name, spec, prof_cols, table, warn, cross_check=not is_json
        )
        null_sql = "" if nullable else " NOT NULL"
        col_defs.append(f"    {name:<24} {typ}{null_sql}")
        if ccomment:
            col_comments.append((name, ccomment))

    col_defs.append(f"    {wm['column']:<24} {wm['ddl']}")

    # Flag source columns the overlay forgot about — silently dropping a column
    # is worse than failing.
    if prof_cols:
        unmapped = [c for c in prof_cols if c not in src_map]
        if unmapped:
            warn.add(f"{table}: profiled columns not mapped in the overlay and therefore "
                     f"NOT loaded: {', '.join(unmapped)}")

    lines.append(f"CREATE TABLE {schema}.{table} (")
    lines.append(",\n".join(col_defs))

    if pk := t.get("primary_key"):
        lines[-1] += ","
        lines.append(f"    CONSTRAINT PK_{table} PRIMARY KEY ({', '.join(pk)})")

    for i, fk in enumerate(t.get("foreign_keys", []), 1):
        lines[-1] += ","
        cols = ", ".join(fk["columns"])
        ref_cols = ", ".join(fk["ref_columns"])
        lines.append(
            f"    CONSTRAINT FK_{table}_{fk['references']}_{i} FOREIGN KEY ({cols}) "
            f"REFERENCES {schema}.{fk['references']} ({ref_cols})"
        )

    lines.append(");")
    lines.append("")

    for name, c in col_comments:
        # Column comments may be a string or a list of lines, matching the
        # table-level `comment` convention. Db2 COMMENT ON takes a single
        # string literal, so join rather than reject.
        text = " ".join(str(x).strip() for x in c) if isinstance(c, list) else str(c)
        safe = text.replace("'", "''")
        # Db2 caps COMMENT ON COLUMN at 254 bytes; over that it is a hard error.
        if len(safe.encode("utf-8")) > 254:
            cut = safe.encode("utf-8")[:251].decode("utf-8", errors="ignore")
            safe = cut + "..."
        lines.append(f"COMMENT ON COLUMN {schema}.{table}.{name} IS '{safe}';")
    if col_comments:
        lines.append("")

    for idx in t.get("indexes", []):
        if ic := idx.get("comment"):
            lines.append(f"-- {ic}")
        lines.append(
            f"CREATE INDEX {schema}.{idx['name']} ON {schema}.{table} ({', '.join(idx['columns'])});"
        )
    if t.get("indexes"):
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--profile", type=Path, default=PROFILE)
    ap.add_argument("--overlay", type=Path, default=OVERLAY)
    ap.add_argument("--out", type=Path, default=DDL_DIR)
    ap.add_argument("--strict", action="store_true", help="treat any warning as fatal")
    args = ap.parse_args()

    profiles = load_json(args.profile, "profile")
    overlay = load_json(args.overlay, "overlay")
    pidx = profile_index(profiles)
    warn = Warn()
    schema = overlay["schema"]
    ts = datetime.now().isoformat(timespec="seconds")

    print(f"Generating DDL for schema {schema}\n")

    # -- 01_schema.sql -----------------------------------------------------
    schema_sql = [HEADER.format(filename="01_schema.sql", ts=ts)]
    schema_sql.append(f"CREATE SCHEMA {schema};\n")
    schema_sql.append(
        "-- A dedicated read-only principal is what Fabric connects as. Least privilege\n"
        "-- is not optional for a regulated bank, and it is the first thing their security\n"
        "-- team will ask about.\n"
        f"-- (Create the OS/LDAP user first; Db2 LUW authenticates against the operating system.)\n"
        f"-- GRANT CONNECT ON DATABASE TO USER FABRICRO;\n"
        f"-- GRANT SELECTIN ON SCHEMA {schema} TO USER FABRICRO;\n"
    )
    (args.out / "01_schema.sql").write_text("\n".join(schema_sql), encoding="utf-8")
    print(f"  wrote {(args.out / '01_schema.sql').relative_to(REPO_ROOT)}")

    # -- 02_tables.sql / 03_tables_optional.sql ----------------------------
    core, optional = [], []
    for t in overlay["tables"]:
        prof = pidx.get(t["source_file"])
        if prof is None and not t.get("optional"):
            warn.add(f"{t['table']}: source file {t['source_file']} was not profiled — "
                     f"types fall back to the overlay only")
        print(f"  {t['table']:<20} <- {t['source_file']}")
        block = emit_table(t, prof, overlay, warn)
        (optional if t.get("optional") else core).append(block)

    body = HEADER.format(filename="02_tables.sql", ts=ts) + "\n" + "\n\n".join(core)
    (args.out / "02_tables.sql").write_text(body + "\n", encoding="utf-8")
    print(f"  wrote {(args.out / '02_tables.sql').relative_to(REPO_ROOT)}")

    if optional:
        body = HEADER.format(filename="03_tables_optional.sql", ts=ts)
        body += ("\n-- Optional tables. Create these only if the corresponding dataset was\n"
                 "-- downloaded. They are separated so a core load never depends on them.\n\n")
        body += "\n\n".join(optional)
        (args.out / "03_tables_optional.sql").write_text(body + "\n", encoding="utf-8")
        print(f"  wrote {(args.out / '03_tables_optional.sql').relative_to(REPO_ROOT)}")

    # -- 99_drop.sql -------------------------------------------------------
    # Reverse order so foreign keys do not block the drops.
    drop = [HEADER.format(filename="99_drop.sql", ts=ts),
            "-- Tear-down, in reverse dependency order. Used by the demo reset script.\n"]
    for t in reversed(overlay["tables"]):
        drop.append(f"DROP TABLE {schema}.{t['table']};")
    drop.append(f"\n-- DROP SCHEMA {schema} RESTRICT;")
    (args.out / "99_drop.sql").write_text("\n".join(drop) + "\n", encoding="utf-8")
    print(f"  wrote {(args.out / '99_drop.sql').relative_to(REPO_ROOT)}")

    if warn.items:
        print(f"\n{len(warn.items)} warning(s). Review them before loading — they are how you find "
              f"out the real files differ from expectation.", file=sys.stderr)
        if args.strict:
            return 1
    else:
        print("\nNo warnings: the overlay and the profiled data agree.")

    print("\nNext: ./scripts/03_prepare.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
