# 13_gateway_register.ps1 — register the gateway cluster against the Fabric tenant.
#
# THIS IS THE ONE STEP THAT CANNOT BE AUTOMATED.
#
# `Add-DataGatewayCluster` is documented: "This command must be run with a user
# based credential." A service principal can authenticate with
# `Connect-DataGatewayServiceAccount -ApplicationId -ClientSecret`, which makes
# the whole thing look automatable, but the cluster-creation cmdlet rejects that
# identity. No Entra app registration, managed identity or SYSTEM context gets
# past it. So: RDP in once, run this, complete the browser sign-in.
#
# How to run it
# -------------
#   1. RDP to the gateway VM  (address and credentials: ~/.nbki-demo/env.sh)
#   2. Open PowerShell 7 AS ADMINISTRATOR  ("pwsh" — not Windows PowerShell)
#   3. cd to wherever you copied this file, then:
#        .\13_gateway_register.ps1 -RecoveryKey (Read-Host 'Recovery key' -AsSecureString)
#
# The recovery key was generated by infra/deploy.sh and is in
# ~/.nbki-demo/gateway-recovery.key on the workstation. Keep it. Without it the
# gateway cannot be restored onto another machine or have a second node added to
# its cluster -- there is no "reset" path, and no copy held by Microsoft.

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [System.Security.SecureString] $RecoveryKey,

    [string] $GatewayName = 'nbki-db2-gw'
)

$ErrorActionPreference = 'Stop'

if (-not (Get-Module -ListAvailable -Name DataGateway)) {
    throw 'DataGateway module not found. Run scripts/12_gateway_install.ps1 first.'
}
Import-Module DataGateway

Write-Output '==> Signing in (a browser window will open)'
Connect-DataGatewayServiceAccount

# ---------------------------------------------------------------------------
# Region.
#
# The instinct is to pin the gateway to the region the Fabric capacity lives in.
# Do not. Microsoft documents: "changing the gateway region will restrict the
# regions in which you can use the gateway. For Power BI, it can only be used in
# the default tenant region." Pinning it to match the capacity can therefore
# make the gateway unusable rather than faster.
#
# Omitting -RegionKey uses the tenant default, which is the correct behaviour.
# The list below is printed for the record only -- note it must be queried AFTER
# authenticating, since it is tenant-specific.
# ---------------------------------------------------------------------------
Write-Output ''
Write-Output '==> Regions available to this tenant (informational; not selecting one)'
Get-DataGatewayRegion | Format-Table -AutoSize | Out-String | Write-Output

Write-Output "==> Creating gateway cluster '$GatewayName' in the tenant default region"
Add-DataGatewayCluster -Name $GatewayName -RecoveryKey $RecoveryKey

Write-Output ''
Write-Output '==> Registered. Clusters visible to this account:'
Get-DataGatewayCluster | Format-Table -Property Id, Name, Status -AutoSize | Out-String | Write-Output

Write-Output ''
Write-Output 'Next: in Fabric, Manage connections and gateways -> the cluster should show Online.'
Write-Output 'Then create the IBM Db2 connection, and set Package collection to NULLID explicitly.'
