#!/usr/bin/env python3
"""
22_deploy_gold.py — build the gold layer from fabric/notebooks/nb_gold.sql.

One source of truth, two artefacts
----------------------------------
`fabric/notebooks/nb_gold.sql` is the gold build: plain T-SQL with `-- MD ---` /
`-- CELL ---` markers, reviewable in a pull request. From it this script deploys
**two** Fabric items, because the demo and the automation want different things:

  * **`nb_gold`** — a native **T-SQL notebook**. This is the artefact to open on
    screen: the gold build in the customer's own language, with its commentary,
    runnable cell by cell in the portal. It is what a DBA in the room recognises.

  * **`nb_gold_runner`** — a PySpark notebook that executes the *same* statements
    against the warehouse over JDBC, one at a time, logging each to
    `lh_silver.gold_build_log`.

Why two, and not just the T-SQL notebook
----------------------------------------
Fabric's `RunNotebook` job API always starts a **Spark** session. A T-SQL
notebook submitted through it is interpreted as Spark SQL and fails with
`System_Cancelled_Session_Statements_Failed` -- verified here twice, including
with a three-statement minimal case. T-SQL notebooks run interactively in the
portal; they are not driveable from the job API.

The runner closes that gap without weakening the story: the statements are
identical, and they execute **in the warehouse engine**, over a normal SQL
connection. Spark is only the thing holding the JDBC connection open.

The per-statement log matters. A SQL script that dies halfway through reports one
generic failure; this reports which statement, with the database's own error.

Usage:
    .venv/bin/python scripts/22_deploy_gold.py            # deploy both, run
    .venv/bin/python scripts/22_deploy_gold.py --no-run   # deploy only
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
import time

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import _fabric as fab  # noqa: E402

SRC = pathlib.Path(__file__).parent.parent / "fabric" / "notebooks" / "nb_gold.sql"
LOG_TABLE = "gold_build_log"


def parse_cells(text: str) -> list[tuple[str, str]]:
    """Split the source on `-- MD ---` / `-- CELL ---` markers."""
    cells: list[tuple[str, str]] = []
    kind: str | None = None
    buf: list[str] = []

    def flush():
        if kind and buf:
            body = "\n".join(buf).strip("\n")
            if body.strip():
                cells.append((kind, body))

    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("-- MD ---"):
            flush()
            kind, buf = "md", []
            continue
        if stripped.startswith("-- CELL ---"):
            flush()
            kind, buf = "code", []
            continue
        if kind == "md":
            buf.append(line[3:] if line.startswith("-- ") else
                       ("" if stripped == "--" else line))
        elif kind == "code":
            buf.append(line)
    flush()
    return cells


def split_statements(sql: str) -> list[str]:
    """Split on statement-terminating semicolons.

    A naive `sql.split(';')` breaks on a semicolon inside a string literal or a
    `--` comment. Neither appears in this file today, which is exactly the kind
    of assumption that stops being true six months from now, so the scan tracks
    both states.
    """
    out, buf = [], []
    in_str = in_comment = False
    i, n = 0, len(sql)
    while i < n:
        ch = sql[i]
        if in_comment:
            if ch == "\n":
                in_comment = False
            buf.append(ch)
        elif in_str:
            buf.append(ch)
            if ch == "'":
                # '' is an escaped quote, not the end of the literal.
                if i + 1 < n and sql[i + 1] == "'":
                    buf.append(sql[i + 1])
                    i += 1
                else:
                    in_str = False
        elif ch == "-" and i + 1 < n and sql[i + 1] == "-":
            in_comment = True
            buf.append(ch)
        elif ch == "'":
            in_str = True
            buf.append(ch)
        elif ch == ";":
            stmt = "".join(buf).strip()
            if stmt:
                out.append(stmt)
            buf = []
        else:
            buf.append(ch)
        i += 1
    tail = "".join(buf).strip()
    if tail:
        out.append(tail)
    # A fragment that is only comments executes to nothing and confuses the log.
    return [s for s in out
            if any(not ln.strip().startswith("--") and ln.strip()
                   for ln in s.splitlines())]


RUNNER_TEMPLATE = '''\
# GENERATED by scripts/22_deploy_gold.py from fabric/notebooks/nb_gold.sql.
# Do not edit here - edit the .sql and redeploy.
#
# Executes the gold build against wh_gold over JDBC, one statement at a time, so
# a failure names the statement and the database's own error rather than a
# single generic "the session was cancelled".
import time, json
import notebookutils

SERVER = {server!r}
DATABASE = {database!r}
WORKSPACE_ID = {workspace_id!r}
SILVER_ENDPOINT_ID = {endpoint_id!r}
SILVER = "abfss://{workspace}@onelake.dfs.fabric.microsoft.com/{silver_lh}.Lakehouse/Tables"

STATEMENTS = json.loads({statements!r})

# Gold reads silver by three-part name through the SQL analytics endpoint, and
# that endpoint lags a Spark write by a background sync. Building too soon means
# gold either cannot see a table or -- far worse -- silently reads the previous
# version and produces a perfectly plausible star schema built on stale numbers.
# Non-fatal: the background sync gets there on its own, and turning a slow sync
# into a hard build failure would be the worse trade.
try:
    import requests
    tok = notebookutils.credentials.getToken("https://api.fabric.microsoft.com")
    r = requests.post(
        f"https://api.fabric.microsoft.com/v1/workspaces/{{WORKSPACE_ID}}"
        f"/sqlEndpoints/{{SILVER_ENDPOINT_ID}}/refreshMetadata?preview=true",
        headers={{"Authorization": f"Bearer {{tok}}"}}, json={{}}, timeout=300)
    print(f"silver endpoint refresh: HTTP {{r.status_code}}")
except Exception as e:
    print(f"silver endpoint refresh skipped ({{str(e)[:120]}}) - continuing")

url = (f"jdbc:sqlserver://{{SERVER}}:1433;database={{DATABASE}};"
       "encrypt=true;trustServerCertificate=false;"
       "hostNameInCertificate=*.datawarehouse.fabric.microsoft.com")

jvm = spark._sc._gateway.jvm
props = jvm.java.util.Properties()
# 'pbi' is the audience the Fabric warehouse endpoint accepts.
props.setProperty("accessToken", notebookutils.credentials.getToken("pbi"))
conn = jvm.java.sql.DriverManager.getConnection(url, props)
stmt = conn.createStatement()

log, failed = [], None
for seq, (cell, label, sql) in enumerate(STATEMENTS):
    t0 = time.time()
    try:
        stmt.execute(sql)
        log.append((seq, cell, label, "OK", "", round(time.time() - t0, 2)))
        print(f"  [{{seq:3d}}] cell {{cell:2d}}  {{label[:54]:54s}} {{time.time()-t0:6.1f}}s")
    except Exception as e:
        msg = str(e)[:900]
        log.append((seq, cell, label, "FAIL", msg, round(time.time() - t0, 2)))
        print(f"  [{{seq:3d}}] cell {{cell:2d}}  {{label[:54]:54s}}  FAILED")
        print(f"        {{msg}}")
        failed = (seq, label, msg)
        break

conn.close()

df = spark.createDataFrame(
    log, "seq int, cell int, label string, status string, error string, seconds double")
df.write.format("delta").mode("overwrite").option("overwriteSchema", "true") \\
  .save(f"{{SILVER}}/{log_table}")

ok = sum(1 for r in log if r[3] == "OK")
print(f"\\n{{ok}}/{{len(STATEMENTS)}} statements succeeded")
if failed:
    raise RuntimeError(f"gold build failed at statement {{failed[0]}} ({{failed[1]}}): {{failed[2]}}")
print("gold build complete")
'''


def label_for(stmt: str) -> str:
    """A short human label, so the log reads as a build plan."""
    head = " ".join(stmt.split())[:90]
    for kw in ("CREATE TABLE", "DROP TABLE IF EXISTS", "ALTER TABLE",
               "INSERT INTO", "WITH", "SELECT"):
        if head.upper().startswith(kw):
            rest = head[len(kw):].strip()
            return f"{kw} {rest.split()[0] if rest else ''}".strip()
    return head[:60]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-run", action="store_true")
    args = ap.parse_args()

    cells = parse_cells(SRC.read_text())
    n_md = sum(1 for k, _ in cells if k == "md")
    print(f"==> {SRC.name}: {len(cells) - n_md} SQL cells, {n_md} markdown cells")

    statements: list[tuple[int, str, str]] = []
    for idx, (kind, body) in enumerate(cells):
        if kind != "code":
            continue
        for s in split_statements(body):
            statements.append((idx, label_for(s), s))
    print(f"    {len(statements)} statements")

    wh_id = fab.ITEMS["wh_gold"]
    wh = fab.api("GET", f"workspaces/{fab.WORKSPACE}/warehouses/{wh_id}")
    server = wh["properties"]["connectionString"]

    # 1. The native T-SQL notebook - the artefact to open on screen.
    tsql_nb = fab.build_ipynb(
        cells, language="sql",
        warehouse={"default_warehouse": wh_id,
                   "known_warehouses": [{"id": wh_id, "type": "Datawarehouse"}]})
    nb_id = fab.deploy_notebook(
        "nb_gold", tsql_nb,
        description="Gold: the dimensional model in T-SQL. Generated from "
                    "fabric/notebooks/nb_gold.sql. Run it interactively in the "
                    "portal - the job API runs notebooks on Spark, so use "
                    "nb_gold_runner for automation.")
    print(f"==> nb_gold (T-SQL, interactive)  {nb_id}")

    # 2. The runner - same statements, executed in the warehouse over JDBC.
    ep = fab.find_item("lh_silver", "SQLEndpoint")
    runner_src = RUNNER_TEMPLATE.format(
        server=server, database="wh_gold", workspace="nbki-db2-demo",
        workspace_id=fab.WORKSPACE, endpoint_id=(ep or {}).get("id", ""),
        silver_lh="lh_silver", log_table=LOG_TABLE,
        statements=json.dumps(statements))
    runner_nb = fab.build_ipynb(
        [("code", runner_src)], language="python",
        lakehouse={"default_lakehouse": fab.ITEMS["lh_silver"],
                   "default_lakehouse_name": "lh_silver",
                   "default_lakehouse_workspace_id": fab.WORKSPACE})
    run_id = fab.deploy_notebook(
        "nb_gold_runner", runner_nb,
        description="Executes the gold T-SQL against wh_gold over JDBC. "
                    "GENERATED - edit fabric/notebooks/nb_gold.sql instead.")
    print(f"==> nb_gold_runner (automation)   {run_id}")

    if args.no_run:
        print("==> --no-run, stopping here")
        return 0

    print("==> refreshing the silver SQL analytics endpoint")
    # Gold reads silver by three-part name. If the endpoint has not caught up
    # with the Spark write, gold builds cleanly on stale data and nothing says so.
    fab.refresh_sql_endpoint("lh_silver")

    print("==> running the gold build")
    t0 = time.time()
    try:
        fab.run_notebook(run_id, timeout_s=5400)
    finally:
        print(f"    {time.time() - t0:.0f}s elapsed")
    print("==> verify with: .venv/bin/python scripts/23_verify_gold.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
